// <auto-generated />
namespace Maison.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Suabangsanphambaohanhthembrand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Suabangsanphambaohanhthembrand));
        
        string IMigrationMetadata.Id
        {
            get { return "202603311151423_Suabangsanphambaohanhthembrand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
