// <auto-generated />
namespace Maison.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class them2bangai : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them2bangai));
        
        string IMigrationMetadata.Id
        {
            get { return "202604051404213_them2bangai"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
